### PR TITLE
Add CloudFormation region note

### PR DESCRIPTION
**Pull request by brennv**
## Issue Type
- Documentation Pull Request

## Summary

Adds note as suggested in this [issue](https://github.com/cristim/autospotting/issues/94#issuecomment-286696488) for CloudFormation users attempting to launch outside us-east-1.

## Code contribution checklist

1. [x] The contribution fixes a single existing github issue, and it is linked
   to it.
1. [ ] The code is as simple as possible, readable and follows the idiomatic Go
  [guidelines](https://golang.org/doc/effective_go.html).
1. [ ] All new functionality is covered by automated test cases so the overall
  test coverage doesn't decrease.
1. [ ] No issues are reported when running `make full-test`.
1. [ ] Functionality not applicable to all users should be configurable.
1. [ ] Configurations should be exposed through Lambda function environment
   variables which are also passed as parameters to the
   [CloudFormation](https://github.com/cristim/autospotting/blob/master/cloudformation/stacks/AutoSpotting/template.json)
   and
   [Terraform](https://github.com/cristim/autospotting/blob/master/terraform/autospotting.tf)
   stacks defined as infrastructure code.
1. [ ] Global configurations set from the infrastructure stack level should also
   support per-group overrides using tags.
1. [ ] Tags names and expected values should be similar to the other existing
   configurations.
1. [ ] Both global and tag-based configuration mechanisms should be tested and
  proven to work using log output from various test runs.
1. [ ] The logs should be kept as clean as possible (use log levels as
  appropriate) and formatted consistently to the existing log output.
1. [ ] The documentation is updated to cover the new behavior, as well as the
   new configuration options for both stack parameters and tag overrides.
1. [ ] A code reviewer reproduced the problem and can confirm the code
  contribution actually resolves it.

### CODE REVIEW

**Comment by xlr-8** [comment]
Thanks, I would have added something like: `:warning:` (:warning:) to make it more 'eye-catching' as it's some limitation

**Comment by xlr-8** [comment]
@brennv do you have a minute, otherwise I can take care of this?

**Comment by coretemp** [comment]
@cristim You can deploy it to other regions by using https://docs.aws.amazon.com/AmazonS3/latest/dev/RequesterPaysBuckets.html.

**Comment by cristim** [comment]
I would still have to keep some 15 buckets în sync, and pay for the storage costs, for very little benefit. Speaking of, din anyone measure the impact of the current situation to the monthly runtime costs? 

For the stable build users I'm going to do it upon demand, as part of the setup support.

**Comment by cristim** [comment]
Now that we use Docker images for the Lambda, the code should now run in any region, so this is no longer relevant.

**Pull request closed without merging**
